### ISSUE TITLE
Hello Matt

### ISSUE THREAD

**Issue by supercrabtree** [eightypop/sc240scale#1]
Hi, I am working for a company in Germany (http://pixformance.com/) using the Tanita Scale. I wanted to ask you a few questions (I assume you are working for Tanita). Could you get hold of me gc@pixformance.com. Sorry for opening an issue, I couldn't find another way to contact you. Feel free to delete it.

Cheers
George

**Comment by eightypop** [comment]
Emailing you.

**Comment by spalenza** [comment]
Hello @whatknight, how are you?

I started a project with Tanita Scale and I find your repository. I saw that you receive scale's data with USB. Is it possible write in serial port to send commands like a start scale, read, get status?

My email is rodolfo.signorelli.spalenza@gmail.com

Thanks.
